### ISSUE TITLE
When doing another place or postcode search

### ISSUE THREAD

**Issue by tidanette** [RochmanReese/AustralianPostcodeFinder#1]
When pressing "Enter" to do another search it shows the below message, which may be confusing:
**------------------------------------------------------------
That selection does not match any of the options. Try Again.**

Other than that, this is so cool! Nice stuff!

**Comment by RochmanReese** [comment]
Thanks for the feedback. I will fix that message

**Comment by RochmanReese** [comment]
Issue now fixed. Removes error message when Enter key is pressed
